[workspace]
name = "carnival"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = "3.10.*"
matplotlib = "==3.10.3"
python-graphviz = "*"
graphviz = "*"
pip = "*"

[pypi-dependencies]
decoupler = "==2.0.6"
omnipath = "==1.0.9"
pydeseq2 = "==0.5.1"
cvxpy = "==1.6.6"
highspy = "==1.11.0"
corneto = "==1.0.0b0"
gurobipy = "*"
