fail_fast: false

default_language_version:
  python: python3

default_stages:
  - commit
  - push

minimum_pre_commit_version: '2.7.1'

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2  # Check https://github.com/astral-sh/ruff-pre-commit/releases for latest
    hooks:
      - id: ruff
        args: [--fix, --format]  # add --preview if you want experimental formatting

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-yaml
