fail_fast: false

default_install_hook_types:
-   pre-commit
-   commit-msg

default_language_version:
  python: python3

default_stages:
-   commit
-   push

minimum_pre_commit_version: '2.7.1'

repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.7.0
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
    -   id: ruff
        args:
        -   --fix
        -   --exit-zero # never fail on diagnostics
        -   --extend-exclude=docs/**.ipynb
    -   id: ruff-format
        args:
        -   --line-length=120

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args:
        -   --maxkb=30720
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-yaml

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]

-   repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-install
