[workspace]
name = "multi_condition_carnival"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = "3.10.*"
anndata = "==0.11.4"
matplotlib = "==3.10.3"
seaborn = "==0.13.2"
dcor = "==0.6"
python-graphviz = "*"
pip = "*"

[pypi-dependencies]
gurobipy = ">=12.0.0"
decoupler = "==2.0.6"
omnipath = "==1.0.9"
pydeseq2 = "==0.5.1"
cvxpy = "==1.6.6"
