name: Build and Deploy Docs

on:
  push:
    branches:
      - dev
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Cache Poetry packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        env:
          POETRY_DYNAMIC_VERSIONING_COMMANDS: install,build
        run: |
          set -e
          pip install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install --with dev,docs

      - name: Debug git state and version
        run: |
          echo "=== Git State Debug ==="
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Current ref: $GITHUB_REF"
          echo "Current ref name: $GITHUB_REF_NAME"
          echo "Tag at HEAD: $(git describe --tags --exact-match HEAD 2>/dev/null || echo 'No exact tag match')"
          echo "Latest tag: $(git describe --tags --abbrev=0 2>/dev/null || echo 'No tags found')"
          echo "=== Version Debug ==="
          poetry version
          echo "CORNETO __version__: $(poetry run python -c 'import corneto; print(corneto.__version__)')"

      - name: Determine doc version and deployment targets
        id: set_version
        run: |
          set -e
          case "${GITHUB_REF}" in
            refs/tags/*)
              version="${GITHUB_REF#refs/tags/}"
              echo "Tag detected: ${version}"
              deploy_to_stable="true"
              is_release="true"
              ;;
            refs/heads/dev)
              version="latest"
              deploy_to_stable="false"
              is_release="false"
              ;;
            *)
              echo "Unexpected branch/ref: ${GITHUB_REF}, skipping deployment"
              exit 0
              ;;
          esac
          echo "doc_version=${version}" >> $GITHUB_OUTPUT
          echo "deploy_to_stable=${deploy_to_stable}" >> $GITHUB_OUTPUT
          echo "is_release=${is_release}" >> $GITHUB_OUTPUT

      - name: Build Docs
        env:
          SPHINX_VERSION_MATCH: ${{ steps.set_version.outputs.doc_version }}
        run: |
          set -e
          poetry run sphinx-build -b html docs docs/_build/html

      - name: Get GitHub Pages URL via GH CLI
        id: pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GH CLI version: $(gh --version)"
          echo "Fetching Pages URL for ${{ github.repository }}…"
          if page_url=$(gh api \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/pages \
            --jq .html_url 2>/dev/null); then
            echo "PAGE_URL=${page_url}" >> $GITHUB_ENV
          else
            default_url="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
            echo "PAGE_URL=${default_url}" >> $GITHUB_ENV
          fi

      - name: Create root redirect to latest
        run: |
          set -e
          mkdir -p temp_root
          touch temp_root/.nojekyll
          if [ -f docs/custom-index.html ]; then
            cp docs/custom-index.html temp_root/index.html
          else
            cp docs/default-index.html temp_root/index.html
          fi

      - name: Deploy content to root
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp_root
          destination_dir: ./
          keep_files: true

      - name: Deploy versioned docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          destination_dir: ${{ steps.set_version.outputs.doc_version }}

      - name: Deploy tagged version to stable folder
        if: ${{ steps.set_version.outputs.deploy_to_stable == 'true' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          destination_dir: stable

      - name: Clean up temporary files
        run: rm -rf temp_root
        
  dispatch-switcher:
      name: Trigger corneto-data update
      needs: build-and-deploy
      runs-on: ubuntu-latest
      steps:
        - name: Notify switcher repo
          uses: peter-evans/repository-dispatch@v3
          with:
            token: ${{ secrets.SWITCHER_PAT }}
            repository: saezlab/corneto-data
            event-type: corneto_updated
            client-payload: |
              {
                "ref": "${{ github.ref }}",
                "sha": "${{ github.sha }}"
              }
