name: Build and Deploy Docs

on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install --with dev,docs

      - name: Build Docs
        run: |
          poetry run sphinx-build -b html docs docs/_build/html

      - name: Determine doc version
        id: set_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
              echo "doc_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
              echo "doc_version=latest" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/heads/dev ]]; then
              echo "doc_version=dev" >> $GITHUB_OUTPUT
          fi

      - name: Generate switcher.json
        run: |
          poetry run python docs/generate_switcher.py

      - name: Deploy Global Switcher
        run: |
          cp docs/switcher.json .

      - name: Deploy versioned docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          destination_dir: ${{ steps.set_version.outputs.doc_version }}
          keep_files: true

      - name: Deploy latest docs to root
        if: ${{ steps.set_version.outputs.doc_version == 'latest' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          destination_dir: ./
          keep_files: true
