# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests

on:
  push:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true # for dynamic versioning
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      env:
        # enable version injection
        POETRY_DYNAMIC_VERSIONING_COMMANDS: install,build
      run: |
        pip install poetry
        poetry self add "poetry-dynamic-versioning[plugin]"
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
